version: 2
jobs:
  simple:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: make simple
      - run: ./bin/simple
  red-black:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: make red-black
      - run: ./bin/red-black

workflows:
  version: 2
  build:
    jobs:
      - simple
      - red-black
